FROM reg.ishopex.cn/paiops-lang-base/nodejs-alpine:20.19 AS base

RUN corepack enable

FROM base AS deps

WORKDIR /app

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

FROM base AS builder

WORKDIR /app

ARG NUXT_APP_NAME
ARG NUXT_APP_TITLE
ARG NUXT_APP_DESCRIPTION
ARG NUXT_PUBLIC_BUSINESS_MODE
ARG NUXT_PUBLIC_API_BASE
ARG NUXT_PUBLIC_API_TIMEOUT
ARG NUXT_PUBLIC_SAAS
ARG NUXT_PUBLIC_COMPANY_ID
ARG NUXT_PUBLIC_DEFAULT_COUNTRY_CODE
ARG NUXT_PUBLIC_UPLOAD_URL
ARG NUXT_PUBLIC_UPLOAD_MAX_SIZE
ARG NUXT_PUBLIC_UPLOAD_ACCEPT
ARG NUXT_PUBLIC_CACHE_TTL
ARG NUXT_PUBLIC_DECORATION_ADMIN_ORIGINS

COPY --from=deps /app/node_modules ./node_modules
COPY . .

ENV NODE_ENV=production
ENV NUXT_APP_NAME=${NUXT_APP_NAME}
ENV NUXT_APP_TITLE=${NUXT_APP_TITLE}
ENV NUXT_APP_DESCRIPTION=${NUXT_APP_DESCRIPTION}
ENV NUXT_PUBLIC_BUSINESS_MODE=${NUXT_PUBLIC_BUSINESS_MODE}
ENV NUXT_PUBLIC_API_BASE=${NUXT_PUBLIC_API_BASE}
ENV NUXT_PUBLIC_API_TIMEOUT=${NUXT_PUBLIC_API_TIMEOUT}
ENV NUXT_PUBLIC_SAAS=${NUXT_PUBLIC_SAAS}
ENV NUXT_PUBLIC_COMPANY_ID=${NUXT_PUBLIC_COMPANY_ID}
ENV NUXT_PUBLIC_DEFAULT_COUNTRY_CODE=${NUXT_PUBLIC_DEFAULT_COUNTRY_CODE}
ENV NUXT_PUBLIC_UPLOAD_URL=${NUXT_PUBLIC_UPLOAD_URL}
ENV NUXT_PUBLIC_UPLOAD_MAX_SIZE=${NUXT_PUBLIC_UPLOAD_MAX_SIZE}
ENV NUXT_PUBLIC_UPLOAD_ACCEPT=${NUXT_PUBLIC_UPLOAD_ACCEPT}
ENV NUXT_PUBLIC_CACHE_TTL=${NUXT_PUBLIC_CACHE_TTL}
ENV NUXT_PUBLIC_DECORATION_ADMIN_ORIGINS=${NUXT_PUBLIC_DECORATION_ADMIN_ORIGINS}

RUN pnpm build

FROM reg.ishopex.cn/paiops-lang-base/nodejs-alpine:20.19 AS runner

WORKDIR /app

ARG NUXT_APP_NAME
ARG NUXT_APP_TITLE
ARG NUXT_APP_DESCRIPTION
ARG NUXT_PUBLIC_BUSINESS_MODE
ARG NUXT_PUBLIC_API_BASE
ARG NUXT_PUBLIC_API_TIMEOUT
ARG NUXT_PUBLIC_SAAS
ARG NUXT_PUBLIC_COMPANY_ID
ARG NUXT_PUBLIC_DEFAULT_COUNTRY_CODE
ARG NUXT_PUBLIC_UPLOAD_URL
ARG NUXT_PUBLIC_UPLOAD_MAX_SIZE
ARG NUXT_PUBLIC_UPLOAD_ACCEPT
ARG NUXT_PUBLIC_CACHE_TTL

ENV NODE_ENV=production
ENV HOST=0.0.0.0
ENV PORT=3000
ENV NUXT_APP_NAME=${NUXT_APP_NAME}
ENV NUXT_APP_TITLE=${NUXT_APP_TITLE}
ENV NUXT_APP_DESCRIPTION=${NUXT_APP_DESCRIPTION}
ENV NUXT_PUBLIC_BUSINESS_MODE=${NUXT_PUBLIC_BUSINESS_MODE}
ENV NUXT_PUBLIC_API_BASE=${NUXT_PUBLIC_API_BASE}
ENV NUXT_PUBLIC_API_TIMEOUT=${NUXT_PUBLIC_API_TIMEOUT}
ENV NUXT_PUBLIC_SAAS=${NUXT_PUBLIC_SAAS}
ENV NUXT_PUBLIC_COMPANY_ID=${NUXT_PUBLIC_COMPANY_ID}
ENV NUXT_PUBLIC_DEFAULT_COUNTRY_CODE=${NUXT_PUBLIC_DEFAULT_COUNTRY_CODE}
ENV NUXT_PUBLIC_UPLOAD_URL=${NUXT_PUBLIC_UPLOAD_URL}
ENV NUXT_PUBLIC_UPLOAD_MAX_SIZE=${NUXT_PUBLIC_UPLOAD_MAX_SIZE}
ENV NUXT_PUBLIC_UPLOAD_ACCEPT=${NUXT_PUBLIC_UPLOAD_ACCEPT}
ENV NUXT_PUBLIC_CACHE_TTL=${NUXT_PUBLIC_CACHE_TTL}

COPY --from=builder /app/.output ./.output

EXPOSE 3000

CMD ["node", ".output/server/index.mjs"]
